
DATASET:
  DATASET_DIR: 'datasets'
  # DATASET_NAME: 'brain-tumor-2'
  DATASET_NAME: '-Brain-Tumor-Detection-2'
  ANNOTATION_FILE_NAME: '_annotations.csv'
  BONE_FRACTURE_DETECTION_DATASET_URL: 'https://universe.roboflow.com/roboflow-100/brain-tumor-m2pbp/dataset/2#'

DATASET_DIRS:
  TRAIN_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/train/
  VALIDATION_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/valid
  TEST_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/test

TRAIN:
  BATCH_SIZE: 32
  NUM_EPOCHS: 100
  LEARNING_RATE: 1e-4
  IMG_SIZE: 240

OUTPUTS:
  OUTPUT_DIR: "output/"
  CONFIG_PIPELINE_PATH: ${OUTPUTS.OUTPUT_DIR}/
  CHECKPOINT_PATH: ${OUTPUTS.OUTPUT_DIR}/checkpoints/
  LOG_DIR: ./logs